### ISSUE TITLE
Player needs to be constructed in same thread as session

### ISSUE THREAD

**Issue by dbischof90** [plietar/python-librespot#1]
When using the player I found out that player and session need to be constructed in one thread and this thread has to be the same thread that uses the player to output to ALSA or other outputs.
Since player.load(id).wait() blocks the whole thread, one has to call a subprocess, load everything locally and launch the player from there

This severely limits the use of the player and, at least in this case, renders functions like pause() useless, since the executing process is blocked. Only way to stop the player is to kill the process.

It would be great if one could find a way to at least pass the player to the multiprocessing protocol to play. I imagine something like launching the player in a new process by passing the created player - object to it and being able to pause it by calling player.pause() in the main thread (or something similar).
Is that possible?

**Comment by plietar** [comment]
So python-librespot should be creating two background threads, one on which the session lives and processes incoming packets, and one on which the player lives and queues audio data to the backend. The `session` and `player` objects are only handles which are used to send messages to the corresponding thread. 

Because the processing happens on another thread, and may depend on network IO, most of the functions return a `Future`. On the rust side, futures are pretty flexible. They can be mapped, joined or selected over for example. On the python side, I've only implemented a single method to `wait` until the future completes.

So back to the `Player::load` function, the future it returns is only used to signal the end of the track. You can ignore it and issue `play`/`pause` commands on the same thread. But this means you won't be able to load the next song once this one ends.

The real issue here is all you can do with a future currently is wait for it, which blocks the current thread. I'm not very familiar with evented programming in Python, so I'm not sure what would be the best way to expose more control, but I'm open to suggestions.

A few ways I can think of :
- Expose a `poll` method which either return `None` or the value, without blocking. This means only busy waiting is available.
- Add a way to register a completion callback on the future. This would probably be executing on the session thread, so Python code has to be careful about synchronisation
- Expose methods to combine futures, such as `join`/`select`. These return a modified future which can be waited on itself. This doesn't integrate well with non-librespot events.
- Integrate librespot with asyncio. This is probably very complicated to do.

**Comment by plietar** [comment]
@dbischof90 I've added support for both `poll` and callbacks. See the `async.py` example.
The callbacks are executed on the session thread, so they must not block. They can make new requests to librespot, or use the `threading` python module to communicate with the rest of the python code.

I'll close this issue, feel free to reopen if you need more functionality.
